version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Euler"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/Puzzles.Tests.FSharp"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
